# Generated by Django 5.1 on 2024-08-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('birthday', models.DateField()),
            ],
        ),
    ]
